### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by maxlapides** [CQLabs/setup-dcm#105]
Node 16 on GitHub Actions is deprecated, so we should upgrade to Node 20

<img width="754" alt="Screenshot 2024-03-28 at 2 58 26 PM" src="https://github.com/CQLabs/setup-dcm/assets/1874682/55ad7d03-8f5b-4afe-b6ee-4f6f2378d1c9">

**Comment by incendial** [comment]
Available in v1.0.4 (or just v1)
