### ISSUE TITLE
Cached version breaks

### ISSUE THREAD

**Issue by RikuVan** [CQLabs/setup-dcm#51]
The use of the cached version breaks on our self hosted  linux runners in github. I copied the action and removed the caching it is fine now. Maybe it would be worth wrapping the extraction from the cache in a try catch and downloading as a backup.

<img width="1111" alt="Screenshot 2023-12-19 at 19 07 32" src="https://github.com/CQLabs/setup-dcm/assets/7317771/fa85a2e5-b7c7-4666-9add-3f10b4875945">

**Comment by incendial** [comment]
It's strange that the github utility tool returns a path that does not exist.

But thanks for the report, will fix that.

**Comment by incendial** [comment]
Fixed in v1.0.3
